name: "Release Beta - Unlocked"
description: "Release an unlocked beta package version"
inputs:
  cumulusci-version:
    description: "version of CumulusCI to install"
    required: false
  sfdx-version:
    description: "version of SFDX to install"
    required: false
  dev-hub-auth-url:
    description: "SFDX auth URL for the Dev Hub"
    required: true
  org-name:
    description: "Org name (see why here https://cumulusci.readthedocs.io/en/stable/unlocked-package.html)"
    required: true
runs:
  using: "composite"
  steps:
    - uses: cumulus-actions/run-flow-scratch@v1
      with:
        dev-hub-auth-url: "${{ inputs.dev-hub-auth-url }}"
        cumulusci-version: "${{ inputs.cumulusci-version }}"
        sfdx-version: "${{ inputs.sfdx-version }}"
        flow-name: release_unlocked_beta
        org-name: "${{ inputs.org-name }}"
